version: '3'
services:
        web:
                image: flask_ava_v1
                build: .
                ports:
                        - "8089:8080"
                volumes:
                        - persistet_volume:/app/volumes
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/avaflaskproject/volumes
